/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Source.TipoOperacion;
import javax.swing.JOptionPane;

/**
 *
 * @author ainokila
 */
public class AniadirOperacionDisponibleView extends javax.swing.JDialog {

    /**
     * Creates new form AniadirOperacionDisponibleView
     */
    public AniadirOperacionDisponibleView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombreOperacion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tiempoOperacion = new javax.swing.JTextField();
        aniadirOperacionBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nombre Operacion:");

        nombreOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreOperacionActionPerformed(evt);
            }
        });

        jLabel2.setText("Tiempo Operacion :");

        aniadirOperacionBtn.setText("Añadir");
        aniadirOperacionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aniadirOperacionBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(aniadirOperacionBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(nombreOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tiempoOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombreOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tiempoOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(aniadirOperacionBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreOperacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreOperacionActionPerformed

    private void aniadirOperacionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aniadirOperacionBtnActionPerformed
        if(nombreOperacion.getText().isEmpty() || tiempoOperacion.getText().isEmpty() ){
             JOptionPane.showMessageDialog(null, "Debes completar los campos");
        }else{
            String cambioComa = tiempoOperacion.getText();
            cambioComa = cambioComa.replace(",", ".");
            if(Double.parseDouble(cambioComa)>0){
                            aux = new TipoOperacion(nombreOperacion.getText(),Double.parseDouble(cambioComa));
                            this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Introduzca cantidad valida o positiva");
            }

        }    
    }//GEN-LAST:event_aniadirOperacionBtnActionPerformed

    public TipoOperacion getTipoOperacionNueva(){
        this.setVisible(true);
        return aux;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aniadirOperacionBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField nombreOperacion;
    private javax.swing.JTextField tiempoOperacion;
    // End of variables declaration//GEN-END:variables
    TipoOperacion aux ;
}
