/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Source.Empresa;
import Source.Operacion;
import Source.OperacionesDiarias;
import Source.Operario;
import Source.TipoOperacion;
import java.awt.Frame;
import java.awt.Window;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author ainokila
 */
public class OperarioView extends javax.swing.JPanel {
    
    private Operario operario;
    private String date;
    private Empresa em;
    
    
    public void setOpererario(Operario op , String date, Empresa em){
        this.em = em;
        
        aniadeOpDiaria.setEnabled(false);
        actualizaTiempoDia.setEnabled(false);
        
        this.operario = op;
        this.date = date;
        this.fillOperacionesPanel(operario.getOperacionesDiarias(date).getListaOperaciones());
        this.name.setText(op.getNombre());
        DecimalFormat df = new DecimalFormat("###.##");
        this.porcDiario.setText(Double.toString(redondear(op.getPorcentajeDia(date), 2)) + "%");
        this.porcTotal.setText(Double.toString(redondear(op.getPorcentajeHistorico(), 2)) + "%");
        operacionCB.removeAllItems();
        tiempoDia.setText(Double.toString(op.getOperacionesDiarias(date).getTiempoRealizado()));
        fechaLabel.setText(date);
        
        if(!op.toString().equals("Operario inexistente")){
                    aniadeOpDiaria.setEnabled(true);
                    if(op.getOperacionesDiarias(date).totalOperaciones()>0){
                          actualizaTiempoDia.setEnabled(true);
                    }

        }
        
        
        ArrayList < TipoOperacion> aux = em.getOperacionesDisponibles().getArrayDis();
        
       for(TipoOperacion a : aux ){
            operacionCB.addItem(a.toString());
       }
       
       repaint();
        repaint();
        revalidate();
    }
    
    

    public double redondear(double numero,int digitos) {
        int cifras=(int) Math.pow(10,digitos);
        return Math.rint(numero*cifras)/cifras; 
    }
    
    private void fillOperacionesPanel (ArrayList<Operacion> aList) {
// Se elimina la información antigua, si la hubiera
        String aux = "<html> <tr> <td> Operacion </td> Tiempo <td> Repeticiones </td> </tr>";
        
        for (Operacion t : aList) {
                aux +="<tr><td>" + t.getTipoOperacion().getNombre() + "</td><td>" + t.getTipoOperacion().getTiempo() + "</td><td>" + t.getRepeticiones() + "</td></tr>";
        }
        
        aux += "</html>";
        muestraDia.setText(aux);
        repaint();
        revalidate();
    }

    /**
     * Creates new form OperarioView
     */
    public OperarioView() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        porcTotal = new javax.swing.JLabel();
        porcDiario = new javax.swing.JLabel();
        aniadeOpDiaria = new javax.swing.JButton();
        operacionCB = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        repeticiones = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        muestraDia = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tiempoDia = new javax.swing.JTextField();
        actualizaTiempoDia = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        fechaLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nombre:");

        name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        name.setText("nombre");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Porcentaje TOTAL:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Porcentaje DIARIO:");

        porcTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        porcTotal.setText("0%");

        porcDiario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        porcDiario.setText("0%");

        aniadeOpDiaria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        aniadeOpDiaria.setText("Añadir Operacion Diaria");
        aniadeOpDiaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aniadeOpDiariaActionPerformed(evt);
            }
        });

        operacionCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Operacion 1" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Operacion :");

        repeticiones.setText("0");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Repeticiones :");

        muestraDia.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        muestraDia.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("TIEMPO DIA : ");

        tiempoDia.setText("tiempo");
        tiempoDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiempoDiaActionPerformed(evt);
            }
        });

        actualizaTiempoDia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        actualizaTiempoDia.setText("ACTUALIZA TIEMPO");
        actualizaTiempoDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizaTiempoDiaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Fecha :");

        fechaLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fechaLabel.setText("fecha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(91, 91, 91)
                        .addComponent(tiempoDia, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(271, 271, 271))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fechaLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(107, 107, 107)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(porcTotal)
                            .addComponent(porcDiario))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(aniadeOpDiaria)
                                .addGap(58, 58, 58))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(actualizaTiempoDia)
                                .addContainerGap())))))
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(operacionCB, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(repeticiones, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(muestraDia, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(name)
                    .addComponent(jLabel2)
                    .addComponent(porcTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(porcDiario)
                    .addComponent(jLabel7)
                    .addComponent(fechaLabel))
                .addGap(41, 41, 41)
                .addComponent(muestraDia, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aniadeOpDiaria, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(operacionCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(repeticiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(tiempoDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(actualizaTiempoDia, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void aniadeOpDiariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aniadeOpDiariaActionPerformed
       if(operario != null){
        int repeticionesS;
        String tipoOperacion ;
        TipoOperacion op;
        
        if (repeticiones.getText()!=null   ){
            repeticionesS = (int) Integer.parseInt(repeticiones.getText());
          
            tipoOperacion = (String) operacionCB.getSelectedItem();
            op = em.getOperacionesDisponibles().operacion(tipoOperacion);
            OperacionesDiarias aux = operario.getOperacionesDiarias(date);
            aux.insertar(new Operacion(op, repeticionesS));
            operario.setOperacionesDiarias(date, aux);
            this.setOpererario(operario, date, em);
            
            repaint();
            revalidate();
           
            
            
        }else{
           JOptionPane.showMessageDialog(null, "Introduzca un valor valido"); 
        }
        repeticiones.setText(null);
       }
        
    }//GEN-LAST:event_aniadeOpDiariaActionPerformed

    private void actualizaTiempoDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizaTiempoDiaActionPerformed
        if(operario != null){
            String cambioComa = tiempoDia.getText();
            cambioComa = cambioComa.replace(",", ".");
            if(Double.parseDouble(cambioComa)>0){
                         operario.getOperacionesDiarias(date).setTiempoRealizado(Double.parseDouble(cambioComa));
                         this.operario.calculaPorcHist();
                         this.setOpererario(operario, date, em);
            }else{
                JOptionPane.showMessageDialog(null, "Introduzca un tiempo valido"); 
            }

            
        }
 
    }//GEN-LAST:event_actualizaTiempoDiaActionPerformed

    private void tiempoDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiempoDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiempoDiaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizaTiempoDia;
    private javax.swing.JButton aniadeOpDiaria;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel muestraDia;
    private javax.swing.JLabel name;
    private javax.swing.JComboBox<String> operacionCB;
    private javax.swing.JLabel porcDiario;
    private javax.swing.JLabel porcTotal;
    private javax.swing.JTextField repeticiones;
    private javax.swing.JTextField tiempoDia;
    // End of variables declaration//GEN-END:variables
}
